"""add resignation_acceptance_date to employee

Revision ID: a20d48751b92
Revises: a4b1077b320f
Create Date: 2026-03-24 14:23:31.657803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20d48751b92'
down_revision = 'a4b1077b320f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resignation_acceptance_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('resignation_acceptance_date')

    # ### end Alembic commands ###
