"""add logo_with_name to company

Revision ID: a4b1077b320f
Revises: d4cca5e8f4c3
Create Date: 2026-03-23 15:41:53.133868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b1077b320f'
down_revision = 'd4cca5e8f4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_with_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('logo_with_name')

    # ### end Alembic commands ###
