"""added bank details to intern

Revision ID: d4cca5e8f4c3
Revises: 1a1d959f1496
Create Date: 2026-03-23 14:43:02.520938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cca5e8f4c3'
down_revision = '1a1d959f1496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_holder', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interns', schema=None) as batch_op:
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('branch')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('account_holder')

    # ### end Alembic commands ###
